PromptPlace/PromptPlace_BE

src/config/passport.ts
src/config/prisma.ts
src/index.ts
src/members/controllers/member.controller.ts
src/members/repositories/member.repository.ts
src/members/routes/member.route.ts
src/members/services/member.service.ts
src/routes/auth.ts

회원 탈퇴 로직 구현 (Soft Delete)
Soft Delete 방식으로 회원 탈퇴 구현
API 요청 시 회원의 status가 1에서 0으로, inactive_date가 생성
src/config/prisma.ts를 통해서 프로젝트 전역에서 사용할 단일 PrismaClient 인스턴스 생성
inactive_date로 부터 얼마나 지나야 데이터베이스에서 완전히 삭제할지 논의해야합니다

feat: 회원탈퇴 로직 구현

---

src/members/controllers/member.controller.ts
src/members/repositories/member.repository.ts
src/members/routes/member.route.ts
src/members/services/member.service.ts

로그인한 사용자가 자신의 회원 정보를 조회할 수 있는 API를 구현했습니다. 이 기능은 `UserProfile` 테이블의 한 줄 소개를 포함한 상세한 사용자 프로필을 반환하며, 다른 사용자의 정보에는 접근할 수 없도록 권한 제어를 포함합니다.
- **API Endpoint**: `GET /api/members/:memberId`
-   기존 `src/members` 모듈 내에 **Controller - Service - Repository** 패턴에 맞춰 기능을 확장했습니다.
-   **Repository (`member.repository.ts`)**
-   `findMemberById` 메서드를 추가했습니다.
-   Prisma의 `include` 옵션을 사용하여, `User` 정보와 관련 `UserProfile` 정보를 한 번의 쿼리로 효율적으로 조회하도록 구현했습니다.
-   **Service (`member.service.ts`)**
-   `getMemberProfile` 메서드를 추가하여 비즈니스 로직을 처리합니다.
-   Repository를 통해 가져온 DB 데이터를 API 명세서에 맞는 응답 형태로 가공합니다.
-   `UserProfile`의 `description` 필드를 `intros` 필드로 매핑합니다.
-   `UserProfile` 정보가 없는 경우, `intros` 필드는 `null`을 반환하도록 처리합니다.
-   요청된 ID의 회원이 존재하지 않을 경우, `404 NotFound` 에러를 발생시킵니다.
-   **Controller …

feat: 회원 정보 불러오기 구현

---

src/prompts/controllers/prompt.like.controller.ts
src/prompts/repositories/prompt.like.repository.ts
src/prompts/routes/prompt.like.route.ts
src/prompts/services/prompt.like.service.ts

사용자가 찜한 프롬프트를 취소할 수 있는 API를 추가했습니다.
JWT 인증이 적용되며, 본인이 찜한 프롬프트에 한해서만 찜 취소가 가능합니다.

Feat: 프롬프트 찜 취소하기 API 구현

---

src/reviews/services/review.service.ts

리뷰를 삭제하려고 할 때 작성한지 30일이 지난 리뷰는 삭제할 수 없는 기능 추가
service 계층
- 현재 시간과 db에 저장된 시간의 차를 이용해 30일이 지났는지 판단
- 30일이 지나지 않았으면 리뷰 삭제
- 30일이 지났으면 403 forbidden에러 반환

feat: 리뷰를 삭제할 수 있는 기간 추가(#53)

---

src/members/controllers/member.controller.ts
src/members/repositories/member.repository.ts
src/members/routes/member.route.ts
src/members/services/member.service.ts

회원 간의 소셜 상호작용을 위한 팔로우/언팔로우 기능을 구현했습니다. 사용자는 다른 사용자를 팔로우하여 소셜 관계를 맺거나, 기존의 팔로우 관계를 취소할 수 있습니다. 이를 통해 플랫폼 내 커뮤니티 기능을 강화하고 사용자 간의 네트워킹을 활성화합니다.
회원 팔로우 및 언팔로우를 위한 REST API를 `Express` 프레임워크 기반으로 구현했습니다.
**API Endpoints**
-   `POST /api/members/follows/{member-id}`: 특정 회원을 팔로우합니다.
-   `DELETE /api/members/follows/{member-id}`: 특정 회원을 언팔로우합니다.
**주요 구현 사항**
-   **Controller (`member.controller.ts`)**:
-   팔로우/언팔로우 요청을 처리하는 `followUser`, `unfollowUser` 핸들러 메서드를 구현했습니다.
-   **Service (`member.service.ts`)**:
-   자기 자신을 팔로우하거나 존재하지 않는 사용자를 대상으로 하는 예외 케이스를 처리했습니다.
-   이미 팔로우 중인 사용자를 다시 팔로우하려고 할 때 `Conflict` 에러를 반환하여 중복 관계 생성을 방지합니다.
-   언팔로우 시, 실제 팔로우 관계가 존재하는지 먼저 확인하여 `NotFound` 에러를 반환하는 로직을 추가했습니다.
-   **Repository (`member.repository.ts`)**:
-   Prisma를 사용하여 `Following` 테이블에 팔로우 관계를 …

Feat: 회원 팔로우, 언팔로우 기능 구현

---

src/members/controllers/member.controller.ts
src/members/dtos/follower.dto.ts
src/members/repositories/member.repository.ts
src/members/routes/member.route.ts
src/members/services/member.service.ts

회원의 팔로워 및 팔로잉 목록을 조회하는 API 기능을 구현했습니다. 이를 통해 특정 사용자의 소셜 관계를 확인할 수 있습니다.
- **`GET /api/members/followers/{member-id}`**
- `MemberRepository`에 `findFollowersByMemberId` 메서드를 추가하여 특정 사용자를 팔로우하는 사용자 목록을 데이터베이스에서 조회합니다.
- `MemberService`에 `getFollowers` 메서드를 추가하여 관련 비즈니스 로직을 처리합니다.
- `MemberController`에 `getFollowers` 메서드를 추가하여 HTTP 요청을 처리하도록 구현했습니다.
- **`GET /api/members/following/{member-id}`**
- `MemberRepository`에 `findFollowingsByMemberId` 메서드를 추가하여 특정 사용자가 팔로우하는 사용자 목록을 조회합니다.
- `MemberService`와 `MemberController`에 각각 `getFollowings` 메서드를 추가하여 비즈니스 로직과 요청을 처리합니다.
- 기존 `tsoa` 자동 생성 방식 대신, `express.Router`를 사용하는 수동 라우팅 방식으로 `src/members/routes/member.route.ts` 파일에 라우트를 설정했습니다.
- `passport-jwt`를 사용하여 모든 API에 대한 인증을 적용했습니다.
- API 응답 DTO(`FollowerDto`)를 정의하여 일관된 데이터 형식을 제공합니다.
- API 요청 시 지정된 …

Feat: 회원 팔로잉, 팔로우 목록 조회

---

src/index.ts
src/inquiries/controllers/inquiry.controller.ts
src/inquiries/dtos/create-inquiry.dto.ts
src/inquiries/repositories/inquiry.repository.ts
src/inquiries/routes/inquiry.route.ts
src/inquiries/services/inquiry.service.ts

사용자가 다른 사용자에게 문의를 보낼 수 있는 '문의하기' API 기능을 구현했습니다.
- **`POST /api/inquiries`**: 인증된 사용자가 다른 사용자에게 문의를 등록하는 API입니다.
- **`inquiries` 모듈 신규 생성**: 문의 기능을 관리하기 위해 `controllers`, `dtos`, `repositories`, `routes`, `services` 디렉토리 및 관련 파일을 새로 생성했습니다.
- **DTO 유효성 검사**: `class-validator`를 사용하여 요청 본문(`receiver_id`, `type`, `title`, `content`)의 유효성을 검사하도록 구현했습니다. 필수 값이 누락될 경우 `400 Bad Request` 에러를 반환합니다.
- **수신자 존재 여부 확인**: 문의를 생성하기 전, `MemberRepository`를 통해 문의를 받는 사용자(receiver)가 실제로 존재하는지 확인하는 로직을 서비스 레이어에 추가했습니다. 수신자가 존재하지 않으면 `404 Not Found` 에러를 반환합니다.
- **라우팅 설정**: `express.Router`를 사용하여 `inquiry.route.ts` 파일에 라우트를 설정하고, `passport-jwt`를 이용한 인증 미들웨어를 적용했습니다.
- `POST /api/inquiries` API 요청 시, 명세에 따라 문의가 성공적으로 등록되고 `201 Created` 상태 코드와 함께 생성된 문의 정보를 반환합니다.
**API Response Example (`POST …

feat: 문의하기 구현

---

src/auth/services/auth.service.ts

사용자 편의성 향상을 위해 Access Token의 유효 기간을 기존 1시간에서 3시간으로 연장했습니다.
- **`src/auth/services/auth.service.ts`** 파일의 `generateTokens` 메서드를 수정했습니다.
- `accessToken`을 생성하는 `jwt.sign` 함수의 `expiresIn` 옵션 값을 `'1h'`에서 `'3h'`로 변경했습니다.
```typescript
// src/auth/services/auth.service.ts
// 수정 전
const accessToken = jwt.sign({ id: user.user_id }, process.env.JWT_SECRET!, {
expiresIn: '1h',
});
// 수정 후
const accessToken = jwt.sign({ id: user.user_id }, process.env.JWT_SECRET!, {
expiresIn: '3h',
});
```
- 이 변경으로 인해 사용자는 한 번 로그인하면 3시간 동안 세션이 유지됩니다.
- 사용자가 더 오랜 시간 동안 로그인 상태를 유지할 수 있게 되어, 잦은 재로그인으로 인한 불편함이 감소합니다.

refactor: accessToken 유효시간 1h -> 3h

---

src/reviews/repositories/review.repository.ts
src/reviews/routes/review.route.ts
src/reviews/services/review.service.ts

관리자 페이지에서 리뷰 삭제 조치를 할 수 있는 기능
관리자는 아무 제약 없이 사람들이 작성한 리뷰를 삭제할 수 있습니다. 이전에 작성했던 리뷰 삭제 api는 일반 user 대상이었기 때문에 service 계층에서 user와 admin을 구분하여 각 기능을  수행하도록 처리했습니다. 
<일반 user일 경우>
- 작성일로부터 30일이 지나면 삭제 불가능
- 자신이 작성한 리뷰만 삭제 가능
<admin일 경우>
- 제약 없이 모든 리뷰 삭제 가능
- admin 계정일 때
- user 계정일 때 사용자가 작성하지 않은 리뷰를  삭제하려고 할 때 에러처리

feat: 관리자 리뷰 삭제 조치(#82)

---

package.json
pnpm-lock.yaml
src/index.ts

백엔드 API에서 프론트엔드(Vercel에 배포된 도메인)의 요청을 허용하도록 CORS 설정을 추가했습니다.
app.use(cors({
origin: ['https://promptplace-fe.vercel.app'],
credentials: true,
}));

Chore: 프론트엔드 CORS 허용

---

src/inquiries/controllers/inquiry.controller.ts
src/inquiries/dtos/create-reply.dto.ts
src/inquiries/repositories/inquiry.repository.ts
src/inquiries/routes/inquiry.route.ts
src/inquiries/services/inquiry.service.ts

- 문의(Inquiry)에 대해 담당자(판매자)가 답변을 등록하는 기능과, 문의를 읽음 상태로 변경하는 기능을 구현했습니다.
- **문의 답변 등록 (`POST /api/inquiries/{inquiry-id}/replies`)**
- 문의를 받은 사용자가 해당 문의에 대한 답변을 등록할 수 있는 API를 구현했습니다.
- `CreateReplyDto`를 추가하여 요청 시 답변 내용(`content`)이 비어있지 않은지 유효성을 검사합니다.
- 서비스 로직에서 아래의 사항을 검증합니다.
1.  요청 대상 문의의 존재 여부
2.  답변을 등록하려는 사용자가 해당 문의의 수신자가 맞는지 권한 확인
- 검증 완료 후, `InquiryReply` 테이블에 답변 내용을 저장하고 생성된 데이터를 반환합니다.
- **문의 읽음 처리 (`PATCH /api/inquiries/{inquiry-id}/read`)**
- 문의를 받은 사용자가 문의의 상태를 '읽음(read)'으로 변경할 수 있는 API를 구현했습니다.
- 서비스 로직에서 아래의 사항을 검증합니다.
1.  요청 대상 문의의 존재 여부
2.  상태를 변경하려는 사용자가 해당 문의의 수신자가 맞는지 권한 확인
- 검증 완료 후, `Inquiry` 테이블의 `status`를 `read`로 업데이트하고 변경된 데이터를 반환합니다.
- 백엔드 API 구현으로, Postman과 같은 API 테스트 도구를 통해 각 기능의 성공 및 에러 케이스를 확인할 수 있습니다.
- **답변 등록 성공 시**: `201 Created` 상태 코드와 함께 생성된 답변 객체가 반환됩니다.
- …

[FEAT] 문의 답변하기, 문의 읽음 처리

---

src/prompts/controllers/prompt.controller.ts
src/prompts/repositories/prompt.repository.ts
src/prompts/routes/prompt.route.ts
src/prompts/services/prompt.service.ts

프롬프트 상세 정보를 조회하는 API를 구현하였습니다.  
사용자는 프롬프트 ID를 통해 해당 프롬프트의 상세 정보를 조회할 수 있습니다.
- `GET /api/prompts/:promptId/details` 라우트 추가
- `prompt.controller.ts`에 `getPromptDetail` 핸들러 추가
- `prompt.repo.ts`에 `getPromptDetailRepo` 함수 구현
- `Prompt` 모델 기준 `user`, `tags`, `models`, `images` 관계 포함
- 응답 데이터 구조는 다음과 같은 정보를 포함
- `title`, `prompt`, `prompt_result`, `description`, `usage_guide`, `price`, `is_free`
- `tags`: 태그명 배열
- `models`: 사용된 모델명 배열
- `images`: 프롬프트 관련 이미지 URL 배열
- `writer`: 작성자 ID, 닉네임, 프로필 이미지 URL
- 정상적으로 반환하는 모습을 보임

#110/feat 프롬프트 상세정보 조회 구현

---

src/members/services/member.service.ts
src/notifications/listeners/notification.listener.ts
src/notifications/repositories/notification.repository.ts
src/notifications/services/notification.service.ts

사용자에게 새 팔로워가 생겼을 때 알림 생성
**- member.service**
- 새 팔로워 정보를 DB에 저장하고 나서 팔로우 알림 이벤트 호출 
**- notification.service**
- createFollowNotification(): 새로운 팔로워 알림 서비스 함수 등록
**- notification.listener**
- 새로운 팔로워 알림 이벤트 리스너 등록

[FEAT]: 새로운 팔로워 알림 생성 구현(#125)

---

src/notifications/listeners/notification.listener.ts
src/notifications/repositories/notification.repository.ts
src/notifications/services/notification.service.ts
src/prompts/services/prompt.service.ts

사용자가 알림 설정한 프롬프터가 새 프롬프트를 업로드했을 때 해당 사용자에게 알림이 가는 기능
- prompt.service
- 새 프롬프트 알림 이벤트 호출
- notification.event
- 새 프롬프트 알림 이벤트 생성
- notification.service
- createPromptNotification(): 새 프롬프트 알림 생성 서비스 함수
- notification.repository 
- findUsersSubscribedToPrompter(): 프롬프트를 업로드한 프롬프터를 알림설정한 사용자ID 목록 추출 함수

[FEAT] 새 프롬프트 알림 생성 구현(#131)

---

pnpm-lock.yaml
src/messages/controllers/message.controller.ts
src/messages/repositories/message.repository.ts
src/messages/routes/message.route.ts
src/messages/services/message.service.ts

수신한 메시지를 조회하는 메시지 목록 API를 구현했습니다.
커서 기반 페이지네이션을 지원하며, 읽음 여부(is_read) 필터도 사용할 수 있습니다.
`{
"message": "메시지 목록 조회 성공",
"messages": [
{
"message_id": 9876,
"title": "프롬프트 가이드라인 위반 경고",
"sender": "관리자",
"created_at": "2025-07-22",
"is_read": false
}
],
"pagination": {
"nextCursor": 9875,
"limit": 10
},
}`

Feat: 메시지 목록 조회 API 구현

---

src/messages/controllers/message.controller.ts
src/messages/routes/message.route.ts
src/messages/services/message.service.ts

사용자가 수신한 메시지를 삭제하는 API를 구현했습니다.
삭제는 실제 DB에서 제거하는 방식이 아닌, is_deleted 플래그를 true로 설정하는 소프트 딜리트 방식입니다.
`{
"message": "메시지가 성공적으로 삭제되었습니다.",
}
`

Feat: 메시지 삭제 API 구현

---

src/messages/controllers/message.controller.ts
src/messages/routes/message.route.ts
src/messages/services/message.service.ts

사용자가 수신한 메시지를 읽음 처리하는 API를 구현했습니다.
요청 시 해당 메시지의 is_read 값을 true로 설정하고, read_at을 현재 시간으로 업데이트합니다.
`{
"message": "메시지가 읽음 처리되었습니다.",
"message_id": 12345,
"is_read": true,
}`

Feat: 메시지 읽음 처리 API 구현

---

src/index.ts

CORS 허용 도메인 추가와 Preflight 요청에 대한 처리를 추가했습니다.

Chore: CORS 설정 추가

---

src/members/services/member.service.ts

회원 정보 조회 및 이력 조회 API의 접근 권한을 수정하여 타인의 정보도 조회할 수 있도록 개선
- **API**: `GET /api/members/{memberId}`
- **기존**: 본인 정보만 조회 가능 (타인 조회 시 403 Forbidden 에러)
- **수정 후**: 모든 사용자가 타인의 정보 조회 가능
- **변경 사항**:
```typescript
// 기존 코드 제거
if (requesterId !== memberId) {
throw new AppError("해당 회원 정보에 접근할 권한이 없습니다.", 403, "Forbidden");
}
```
- **API**: `GET /api/members/{memberId}/histories`
- **기존**: 본인 이력만 조회 가능 (타인 조회 시 403 Forbidden 에러)
- **수정 후**: 모든 사용자가 타인의 이력 조회 가능
- **변경 사항**:
```typescript
// 기존 코드 제거
if (requesterId !== memberId) {
throw new AppError("해당 회원의 이력을 조회할 권한이 없습니다.", 403, "Forbidden");
}
```
**회원 정보 조회 시 반환 데이터**:
```json
{
"member_id": 123,
"email": "user@example.com",
"name": "홍길동",
"nickname": "프롬프트러버", 
"intros": "안녕하세요! 프롬프트 전문가입니다.",
"created_at": "2024-01-15T10:30:00Z", …
```

Fix/#168 특정 회원 정보 조회 및 이력 조회 API 접근 권한 수정

---

src/members/services/member.service.ts

회원 이력 조회 API의 데이터 조회 로직을 개선하여 UserHistory 테이블을 직접 조회하도록 변경
- **복잡한 다중 테이블 조회**: `purchase`, `prompt`, `withdrawRequest` 3개 테이블을 각각 조회
- **데이터 변환 로직**: 각 테이블 데이터를 "이력" 형태로 가공하는 복잡한 매핑 로직
- **실제 이력 테이블 미사용**: `UserHistory` 테이블에 데이터가 있어도 조회하지 않음
- **성능 이슈**: 불필요한 다중 쿼리 실행
**API**: `GET /api/members/{memberId}/histories`
**변경 전**:
```typescript
async getHistories(requesterId: number, memberId: number) {
// 3개 테이블 조회
const purchases = await this.memberRepository.findPurchasesByUserId(memberId);
const uploads = await this.memberRepository.findPromptsByUserId(memberId);
const withdrawals = await this.memberRepository.findWithdrawalsByUserId(memberId);
// 복잡한 데이터 변환 로직 (40+ 라인)
const purchaseHistories = purchases.map((p) => ({ /* 변환 로직 */ }));
const uploadHistories = uploads.map((p) => ({ /* 변환 …
```

fix: 회원 이력 조회 로직 변경

---

src/auth/controllers/auth.controller.ts
src/auth/dtos/complete-signup.dto.ts
src/auth/services/auth.service.ts

프론트엔드 연동을 위한 소셜 로그인 토큰 교환 API를 구현했습니다. 기존 Passport 기반 리다이렉트 방식에서 프론트엔드 주도 방식으로 변경하여, 프론트엔드에서 인증코드를 받아 백엔드로 전송하는 구조로 개선했습니다.
- `POST /api/auth/kakao/token` - 카카오 인증코드로 토큰 교환
- `POST /api/auth/google/token` - 구글 인증코드로 토큰 교환  
- `POST /api/auth/naver/token` - 네이버 인증코드로 토큰 교환
- **카카오**: 2단계 로그인 (인증 → 추가 정보 입력)
- 1단계: 카카오 인증 후 임시 사용자 생성 (name 필드 빈 문자열)
- 2단계: 프론트엔드에서 name 입력 후 `complete-signup` API 호출
- **구글/네이버**: 1단계 로그인 (인증 → 바로 완료)
- `description`, `sns_url` 필드 제거 (소셜 로그인 시 불필요)
- 카카오 로그인 전용으로 단순화
- `name`, `nickname`, `email` 필드만 유지
- `name` 필드가 필수인데 카카오 로그인 시 빈 문자열로 설정하여 스키마 위반 방지
- 소셜 로그인 후 `complete-signup`에서 실제 name 값으로 업데이트
```json
// POST /api/auth/kakao/token 응답
{
"access_token": "JWT토큰",
"refresh_token": "리프레시토큰", 
"user": {
"user_id": 1,
"email": "user@kakao.com",
"nickname": …
```

feat: 소셜 로그인 토큰 교환 API 구현 및 프론트엔드 연동 준비 완료

---

src/announcements/controllers/announcement.controller.ts
src/announcements/repositories/announcement.repository.ts
src/announcements/routes/announcement.route.ts
src/announcements/services/announcement.service.ts
src/tips/controllers/tip.controllers.ts
src/tips/repositories/tip.repository.ts
src/tips/routes/tip.route.ts
src/tips/services/tip.service.ts

프롬프트 팁 / 공지사항 상세정보 조회 구현
- 프롬프트 팁 및 공지사항의 상세정보 조회 API가 누락되어 새로 작성하였습니다.
- 프롬프트 팁 및 공지사항의 상세정보 조회
- 정상적으로 작동 확인 완료

feat/#175 프롬프트 팁 및 공지사항 상세정보 조회 구현

---

src/auth/controllers/auth.controller.ts
src/auth/routes/auth.route.ts

프론트엔드 연동을 위한 소셜 로그인 토큰 교환 API를 구현했습니다. 기존 Passport 기반 리다이렉트 방식에서 프론트엔드 주도 방식으로 변경하여, 프론트엔드에서 인증코드를 받아 백엔드로 전송하는 구조로 개선했습니다.
- `POST /api/auth/kakao/token` - 카카오 인증코드로 토큰 교환
- `POST /api/auth/google/token` - 구글 인증코드로 토큰 교환  
- `POST /api/auth/naver/token` - 네이버 인증코드로 토큰 교환
- **카카오**: 2단계 로그인 (인증 → 추가 정보 입력)
- 1단계: 카카오 인증 후 임시 사용자 생성 (name 필드 빈 문자열)
- 2단계: 프론트엔드에서 name 입력 후 `complete-signup` API 호출
- **구글/네이버**: 1단계 로그인 (인증 → 바로 완료)
- `description`, `sns_url` 필드 제거 (소셜 로그인 시 불필요)
- 카카오 로그인 전용으로 단순화
- `name`, `nickname`, `email` 필드만 유지
- `name` 필드가 필수인데 카카오 로그인 시 빈 문자열로 설정하여 스키마 위반 방지
- 소셜 로그인 후 `complete-signup`에서 실제 name 값으로 업데이트
- 각 소셜 로그인 API에 대한 상세한 Swagger 문서 작성
- 요청/응답 스키마, 에러 케이스, 예시 데이터 포함
- 프론트엔드 개발자를 위한 명확한 API 명세서 제공
```json
// POST /api/auth/kakao/token 응답
{
"message": "카카오 로그인이 …
```

feat: 소셜 로그인 토큰 교환 API 구현

---

src/inquiries/repositories/inquiry.repository.ts
src/inquiries/services/inquiry.service.ts

TypeScript 컴파일 에러를 해결하여 코드의 타입 안전성을 향상시키는 수정 사항입니다.
**문제 상황:**
- `src/inquiries/services/inquiry.service.ts`에서 `inquiry.sender`와 `inquiry.receiver`가 `null`일 수 있다는 TypeScript 에러 발생
- 에러 발생 위치: 53번째, 55번째, 143번째 줄
**해결 방법:**
1. **Repository 레벨에서 null 체크 추가**
- `findInquiryById`: `sender`와 `receiver`가 null인 경우 Error를 던지도록 수정
- `findReceivedInquiries`: `sender`가 null인 경우 Error를 던지도록 수정
2. **Service 레벨에서 null 체크 추가**
- `getReceivedInquiries`: `sender`가 null인 경우 `AppError`를 던지도록 수정
**수정된 파일:**
- `src/inquiries/repositories/inquiry.repository.ts`
- `src/inquiries/services/inquiry.service.ts`
- ✅ TypeScript 컴파일 에러 해결
- ✅ `inquiry.sender`와 `inquiry.receiver`의 null 가능성 제거
- ✅ 타입 안전성 향상
- ✅ 런타임에서 사용자 정보 누락 시 명확한 에러 메시지 제공
**에러 메시지 예시:**
- "사용자 정보를 찾을 수 없습니다. sender: not found, receiver: not found"
- …

fix: inquiries.service에서 나온 에러 해결

---

src/purchases/controller/purchase.controller.ts
src/purchases/dtos/purchase.dto.ts
src/purchases/repositories/purchase.request.repository.ts
src/purchases/routes/purchase.request.route.ts
src/purchases/services/purchase.service.ts

사용자의 결제 내역을 조회하는 API를 구현했습니다.
해당 API는 인증된 사용자의 결제 히스토리를 조회하며, 프롬프트 정보와 판매자 정보를 함께 반환합니다.
- **GET /api/purchases** 엔드포인트 추가
- 요청 헤더의 `Authorization: Bearer {access_token}`을 통해 사용자 인증
- 사용자가 구매한 프롬프트 목록과 결제 정보 조회
- **응답 형식**
```json
{
"message": "결제 내역 조회 성공",
"purchases": [
{
"prompt_id": 1024,
"title": "시장조사 프롬프트",
"price": 3000,
"purchased_at": "2025-07-04T09:30:00.000Z",
"seller_nickname": "분석가123",
"pg": "kakaopay"
}
],
}

Feat: 결제 내역 조회 API 구현

---

src/withdrawals/controllers/withdrawal.available.controller.ts
src/withdrawals/dtos/withdrawal.available.dto.ts
src/withdrawals/repositories/withdrawal.repository.ts
src/withdrawals/routes/withdrawal.route.ts
src/withdrawals/services/withdrawal.available.service.ts
src/withdrawals/services/withdrawal.service.ts

로그인한 사용자의 **출금 가능 금액**을 조회하는 API를 추가했습니다.
`GET /api/settlements/withdrawals/available` 엔드포인트를 통해 정산 완료 금액에서 이미 출금 요청(대기 + 완료)된 금액을 제외한 값을 반환합니다.
* 인증: `Authorization: Bearer {access_token}`
* 응답:
```json
{
"message": "출금 가능 금액 조회 성공",
"available_amount": 12345,
}
```
* **엔드포인트**
* `GET /api/settlements/withdrawals/available`
* 인증 미들웨어 적용(미인증 시 `401 Unauthorized`)
* **계산 로직**
* 정산 합계: `Settlement`에서 `status = 'SUCCEED'` 인 레코드의 `amount` 합계
* 출금 합계: `WithdrawRequest`에서 `status IN ('PENDING', 'SUCCEED')` 인 레코드의 `amount` 합계
* `available = max(0, 정산합계 - 출금합계)`로 산출(음수 방지)
* **레이어드 구조**
* `dtos/withdrawalAvailable.dto.ts`: 응답 DTO 정의
* `repositories/withdrawal.repository.ts`:
* `getUserTotalEarnings(userId)` — 완료된 정산 합계 조회
* `getUserTotalWithdrawn(userId)` — 대기/완료 상태의 출금 합계 조회
* …

Feat: 출금 가능 금액 조회 API 구현

---

prisma/migrations/20250814_baseline_from_prod/migration.sql
prisma/schema.prisma
src/withdrawals/controllers/withdrawal.controller.ts
src/withdrawals/dtos/withdrawal.dto.ts
src/withdrawals/services/withdrawal.service.ts

출금 요청 시 **사용자 가용 금액 전체를 자동 출금**하도록 로직을 수정했습니다.
또한 **최소 출금 가능 금액을 10,000원**으로 상향하여, 가용 금액이 10,000원 미만이면 출금이 불가합니다.
* 엔드포인트: `POST /api/settlements/withdrawals` (동일)
* 요청 바디: **없음** (기존 `amount`는 사용하지 않음)
* 가용 금액 계산:
`Settlement(status='SUCCEED') 합계` − `WithdrawRequest(status IN ('PENDING','SUCCEED')) 합계`
* **Service**
* `MIN_WITHDRAWAL = 10_000` 적용
* 가용 금액 < 10,000 → `400 InvalidWithdrawalAmount`
* 가용 금액 ≥ 10,000 → **가용 금액 전액**으로 `WithdrawRequest` 생성 (`status: 'Succeed'` 사용)
* **Repository**
* `getUserTotalEarnings(userId)` : `Settlement`의 `status='SUCCEED'` 합계 조회
* `getUserTotalWithdrawn(userId)` : `WithdrawRequest`의 `status IN ('PENDING','SUCCEED')` 합계 조회
* `createWithdrawalRequest(userId, amount)` : 계산된 전체 가용 금액으로 생성
* **Controller**
* 요청 바디의 `amount` **무시**
* 에러 메시지/코드 최신화(10,000원 기준) …

Fix: 출금 요청 로직 수정

---

prisma/migrations/20250815_add_bank/migration.sql
prisma/schema.prisma

사용자가 본인 명의의 계좌만 등록할 수 있도록 하기 위해 계좌 관련 테이블을 추가하고,
계좌 소유자 검증이 가능하도록 스키마를 설계했습니다.
- `PreRegisteredAccount` 모델 추가
- 은행 코드, 계좌번호, 예금주, 소유자(`owner_user_id`) 필드 정의
- 소유자 기준 중복 방지 유니크 제약(`@@unique`)
- `Bank` 및 `User`와의 관계 설정
- `(id, owner_user_id)` 복합 유니크 키 추가 → 복합 FK 타깃
- `UserBankAccount` 모델 추가
- 유저당 1개 계좌만 등록 가능(`user_id` @unique)
- 같은 사전 등록 계좌 재사용 금지(`preregistered_id` @unique)
- `(preregistered_id, user_id)` 복합 유니크 → 본인 소유 계좌만 FK 등록 가능
- `User` 및 `PreRegisteredAccount`와의 관계 설정
- 본인 명의 계좌만 등록 가능하도록 `(preregistered_id, user_id) -> (id, owner_user_id)` 복합 FK 구성
> 이 스키마를 기반으로 계좌 등록 API 구현 시, DB 레벨에서 소유자 불일치 계좌 등록을 차단합니다.

Feat: 계좌 관련 스키마 추가

---

src/accounts/controllers/account.controller.ts
src/accounts/dtos/account.dto.ts
src/accounts/repositories/account.repository.ts
src/accounts/routes/account.route.ts
src/accounts/services/account.service.ts

사용자가 본인의 계좌 정보를 조회할 수 있는 **GET `/api/members/me/accounts`** API를 구현했습니다.
인증된 사용자만 접근 가능하며, 등록된 계좌 정보를 반환합니다.
* ✅ **계좌 조회 API 구현 (`GET /api/members/me/accounts`)**
* JWT 인증된 사용자만 요청 가능 (`Authorization: Bearer {token}`)
* 등록된 계좌 정보가 없을 경우 `404 NotFound` 에러 반환
* ✅ **DTO, Repository, Service, Controller, Route 구조로 분리**
* ✅ **`UserBankAccount` → `PreRegisteredAccount` → `Bank` 테이블 조인 조회**
* ✅ **응답 형식 명세에 맞춰 정리**
```json
{
"message": "계좌 정보를 불러왔습니다.",
"data": {
"account_id": 123,
"bank_code": "090",
"bank_name": "카카오뱅크",
"account_number": "3333222111000",
"account_holder": "홍길동"
},
}
```
* ✅ **예외 처리**
* 미인증 요청 시: `401 Unauthorized`
* 등록된 계좌 없을 시: `404 NotFound`
* 서버 오류 발생 시: `500 Internal Server Error`
*

Feat: 계좌 정보 불러오기 API 구현

---

src/config/passport.ts
src/members/routes/member.route.ts

회원 탈퇴 후에도 JWT 토큰이 유효하여 다른 서비스에 접근할 수 있는 보안 취약점을 해결했습니다. Passport JWT Strategy에서 사용자 상태를 확인하여 탈퇴한 회원(`status: false`)의 모든 API 접근을 자동으로 차단하도록 개선했습니다.
- **기존**: 사용자 존재 여부만 확인 (`!user`)
- **개선**: 사용자 존재 여부 + 활성 상태 확인 (`!user || !user.status`)
- **위치**: `src/config/passport.ts`의 JWT Strategy
- **모든 인증이 필요한 API**에 자동 적용
- **별도 미들웨어 추가 불필요**
- **기존 코드 구조 유지**
```typescript
// 기존 코드
if (!user) return done(null, false);
// 개선된 코드
if (!user || !user.status) {
return done(null, false);
}
```
- ✅ **탈퇴한 회원 자동 차단**: `status: false`인 사용자 즉시 차단
- ✅ **전체 API 보안**: 인증이 필요한 모든 엔드포인트에 자동 적용
- ✅ **즉시 적용**: 회원 탈퇴 직후 다음 API 호출부터 차단
```json
// 탈퇴한 회원이 API 호출 시
{
"error": "Unauthorized",
"message": "Unauthorized",
"statusCode": 401
}
```
- **회원 관련**: 프로필 조회, 수정, 팔로우 등
- **프롬프트 관련**: 작성, 수정, 삭제 등
- **결제 관련**: 구매, …

feat: 회원 탈퇴 로직 추가

---

src/config/social/google.ts
src/config/social/naver.ts

회원 탈퇴 후 동일한 이메일로 소셜 로그인을 시도할 때 발생하는 문제를 해결했습니다. 탈퇴한 사용자(`status: false`)가 재로그인 시도 시 자동으로 계정을 재활성화하여, 새로운 계정을 생성하지 않고도 안전하게 서비스를 이용할 수 있도록 개선했습니다.
- **네이버**: `src/config/social/naver.ts` 수정
- **구글**: `src/config/social/google.ts` 수정  
- **카카오**: `src/config/social/kakao.ts` 수정
```typescript
if (user) {
if (!user.status) {
// 탈퇴한 사용자인 경우 재활성화
user = await prisma.user.update({
where: { email },
data: {
status: true,
inactive_date: null,
updated_at: new Date(),
},
});
}
return done(null, user);
}
```
- **이메일 unique 제약조건** 유지
- **기존 사용자 데이터** 보존
- **새로운 계정 생성** 방지
- **Passport JWT Strategy**에서 `!user.status` 체크
- **탈퇴한 사용자** 자동 차단
- **재활성화 후** 정상 서비스 이용 가능
```
1. 사용자 A가 회원 탈퇴
↓
2. status: false, inactive_date 설정
↓
3. 동일한 이메일로 소셜 로그인 시도
↓
4. 자동으로 계정 재활성화
↓
5. 정상적으로 서비스 이용 가능
```
```json
// 재활성화 …
```

fix: 회원 탈퇴 로직 수정

---

src/middlewares/errorHandler.ts

401 Unauthorized 전역 에러로 등록
```
// 401 에러 통일 처리
if (
err.statusCode === 401 ||
err.message === "Unauthorized" ||
err.name === "JsonWebTokenError" ||
err.name === "TokenExpiredError"
) {
res.status(401).json({
error: "Unauthorized",
message: "로그인이 필요합니다.",
statusCode: 401,
});
return;
}
```

fix: 401 Unauthorized 전역 에러로 등록

---

src/members/dtos/update-intro.dto.ts

한줄 소개 PATCH 빈 문자열 허용
```
import { IsOptional, IsString, Length } from "class-validator";
export class UpdateIntroDto {
@IsString({ message: "한줄 소개는 문자열이어야 합니다." })
@IsOptional()
@Length(0, 100, {
message: "한줄 소개는 100자 이하로 입력해주세요.",
})
intro!: string;
}
```

FIX: 한줄 소개 PATCH 빈 문자열 허용

---

Caddyfile

Caddyfile에서 백엔드 API 도메인을 `api.promptplace.kr`에서 `promptplace.kro.kr`로 수정했습니다.  
프론트엔드에서 호출하는 실제 도메인과 일치하도록 설정을 변경했습니다.
- Caddyfile의 사이트 블록 도메인 변경:  
- 기존: `api.promptplace.kr`  
- 변경: `promptplace.kro.kr`
- reverse proxy 대상(`app:3000`)은 동일하게 유지
- 보안 헤더 및 헬스체크 설정은 기존과 동일하게 유지
- `https://promptplace.kro.kr`에서 API 요청 시 더 이상 308 리다이렉트 발생하지 않음
- 브라우저 CORS 에러 해소 및 정상 응답 확인  
- 도커 로그 및 `curl` 테스트로 헬스체크/프록시 동작 검증 완료
- 로컬 개발 환경에서는 `localhost:3000`, `localhost:5173` CORS 허용 여부를 분리(`NODE_ENV` 기준)하는 것이 좋을지 의견 필요

[FIX] :caddyfile 서버 api 도메인 수정(#290)
