- package.json
- pnpm-lock.yaml
- src/config/passport.ts
- src/config/social/google.ts
- src/config/social/naver.ts
- src/routes/auth.ts
- src/routes/auth/google.ts
- src/routes/auth/naver.ts
네이버 로그인/회원가입 구현 & 소셜 로그인 로직 분할
네이버 로그인/회원가입 구현 & 소셜 로그인 로직 분할
> [feat/#2]네이버 로그인/회원가입 구현 및 로직 분할

- package-lock.json
- src/config/constants.ts
- src/config/prisma.ts
- src/index.ts
- src/prompts/dtos/search-prompt.dto.ts
- src/prompts/prompt.controller.ts
- src/prompts/prompt.repository.ts
- src/prompts/prompt.route.ts
- src/prompts/prompt.service.ts
pormpt 검색 기능 구현과 동시에 파일에 프롬프트 관련 API를 구현할 수 있도록 제작하였습니다.
요청받은 API 정보에 기반하여 prompt를 검색하는 기능
prompt controller/ repository / service / dto / route 구현
확인 후 기능적으로 수정해야할 부분이 있다면 남겨주시기 바랍니다!
> #6 [FEAT] 프롬프트 검색 구현

- src/prompts/controllers/prompt.download.controller.ts
- src/prompts/dtos/prompt.download.dto.ts
- src/prompts/repositories/prompt.download.repository.ts
- src/prompts/routes/prompt.downlaod.route.ts
- src/prompts/services/prompt.download.service.ts
> [Feat/#9] 무료 프롬프트 다운로드 API 구현

- src/reviews/controllers/review.controller.ts
- src/reviews/dtos/review.dtos.ts
리뷰 수정 화면 가져오는 api의 응답 구조 수정 
- data 객체필드가 두 번 나오는 중첩된 응답 구조를 하나로 통일
- 응답 속성에 prompt_title 추가
> [FIX]: 리뷰 수정하기 응답 구조 수정, 속성 추가(#62)

- package-lock.json
- src/tip/routes/tip.route.ts
TIP router의 JWT 인증 미들웨어를 추가했습니다
> #69 [FIX] JWT 인증 미들웨어 추가

- src/reviews/controllers/review.controller.ts
- src/reviews/dtos/review.dtos.ts
- src/reviews/repositories/review.repository.ts
- src/reviews/routes/review.route.ts
- src/reviews/services/review.service.ts
사용자가 받은 모든 리뷰를 조회하는 기능
1. cursor와 limit을 사용한 페이지네이션
2. 아래 api의 모든 응답 구조를 명세서에 맞도록 수정함
- 리뷰 목록
- 리뷰 등록
- 리뷰 삭제
- 리뷰 수정
- 내가 작성한 리뷰
> feat: 내가 받은 리뷰 목록 구현(#66)

- src/prompts/controllers/prompt.controller.ts
- src/prompts/repositories/prompt.repository.ts
프롬프트 검색 / 상세보기 코드 수정
코드에 오류가 생겨 해당 부분 수정 완료했습니다.
-정상 작동 모습
> fix/#111 프롬프트 검색 / 상세보기 코드 수정

- src/inquiries/controllers/inquiry.controller.ts
- src/inquiries/dtos/create-inquiry.dto.ts
- src/inquiries/services/inquiry.service.ts
- src/members/controllers/member.controller.ts
inquiry.controller, create-inquiry.dto, inquiry.service, member.controller에서 AppError.ts 사용하면서 생긴 에러 해결
> fix: AppError.ts 에러 해결

- src/members/dtos/follower.dto.ts
follower.dto에서 생긴 linter 오류 수정
src/members/dtos/follower.dto에서 생긴 linter 오류 수정
> fix: follower.dto linter 오류 해결

- .github/workflows/deploy-main.yml
Cannot Get 오류를 해결하기 위해 TS 빌드 과정을 워크플로우에 넣었습니다.
문제를 해결하기 위해 메인 브랜치 파일을 실행 하였으나 문제가 없었고, 서버에 문제가 있다고 판단
ssh로 접속하여 확인해보니 실제 실행되는 서버인 dist폴더의 파일은 전부 옛날 코드임을 확인
TS로 된 파일을 JS로 컴파일 후 dist 폴더에 넣기 때문에 이 부분이 잘못되었다고 판단했고
워크플로우 파일을 확인한 결과 TS -> JS 빌드 코드가 없어 추가 했습니다.
> Fix: TS 빌드 추가 (#141)

- src/prompts/controllers/prompt.controller.ts
- src/prompts/dtos/create-prompt.dto.ts
- src/prompts/dtos/update-prompt.dto.ts
- src/prompts/repositories/prompt.repository.ts
프롬프트 업로드, 수정 API에서 모델 복수 선택을 허용했습니다
프롬프트 업로드, 수정 API에서 모델 복수 선택을 허용했습니다
프롬프트 업로드, 수정 , 삭제 API에 트랜잭션을 추가해 안정성을 높였습니다
/ health check 변경
> fix: 모델 복수 선택 허용 및 트랜잭션 추가 (#145)

- src/notifications/controllers/notification.controller.ts
- src/notifications/listeners/notification.listener.ts
- src/notifications/routes/notification.route.ts
- src/notifications/services/notification.service.ts
- src/prompts/services/prompt.service.ts
- src/reports/controllers/report.controller.ts
- src/reports/dtos/report.dto.ts
- src/reports/routes/report.route.ts
- 신고 api 스웨거 수정
- 알림 api 스웨거 작성
- 새 프롬프트 업로드 알림에서 link_url이 기존에는 profile/.. 경로로 잘못되어있어서 prompt/...로  수정
> [DOCUMENT] 신고, 알림 스웨거 작성

- src/prompts/controllers/prompt.controller.ts
수정 : request body 필드 검사시 price항목을 string으로 처리해 오류가 남
->price항목은 따로 처리
> fix: price필드 number처리(#183)

- src/prompts/routes/prompt.route.ts
> #179 [ fix ] 프롬프트 검색 request type 변경

- src/prompts/repositories/prompt.repository.ts
프롬프트 조회 API 응답 추가
프롬프트 조회 API 응답 중 views 컬럼이 누락되어 추가했습니다.
잦은 수정 죄송합니다 ㅡ.ㅡ;
> #184 [FIX] 프롬프트 조회 API 응답 추가

- src/prompts/repositories/prompt.repository.ts
프롬프트 상세보기 재수정
-기존의 repository 코드가 필요한 정보를 누락하여 전달하는 일이 발생하여 필요한 정보를 모두 담을 수 있도록 수정하였습니다.
> #185 [FIX] 프롬프트 상세보기 재수정

- src/index.ts
'http://52.79.208.145:3000',
'http://52.79.208.145' 주소 추가
기존 문제점: 모든 post 요청에 cors 에러 발생
> [BUG] cors설정에 IP주소 추가

- prisma/schema.prisma
타입스크립트 빌드 message.resposity.ts에서 발생하는 오류를 해결했습니다.
Message와 User 사이에 relation 추가했습니다.
> Fix: Message 프리즈마 수정

- src/prompts/controllers/prompt.controller.ts
- src/prompts/dtos/search-prompt.dto.ts
- src/prompts/repositories/prompt.repository.ts
- src/tips/dtos/tip.dto.ts
- src/tips/routes/tip.route.ts
- 프롬프트 팁 API의 DTO 코드가 업데이트 되지 않아 일부 정보만을 필터링하여 전달하는 문제를 수정하였습니다.
- 기존의 프롬프트 검색 조건의 경우 검색어가 필수 조건이었지만, 검색어 없이 필터 조건만으로도 검색이 가능하도록 수정하였습니다.
-  //Tip DTO 수정
return {
tips: rawTips.map((tip) => ({
tip_id: tip.tip_id,
writer_id: tip.writer_id,
title: tip.title,
content: tip.content,
is_visible: tip.is_visible,
file_url: tip.file_url,
created_at: tip.created_at.toISOString(),
updated_at: tip.updated_at.toISOString(),
})),
-    // 필수 값(키워드) 유효성 검증 삭제
if (typeof keyword !== "string" || !keyword.trim()) {
return res.status(400).json({ message: "검색 결과가 없습니다." });
}
> Fix/#186 프롬프트 팁 API 수정 & 프롬프트 검색 조건 변경

- src/prompts/controllers/prompt.controller.ts
- src/prompts/repositories/prompt.repository.ts
프롬프트 구매 이력이 있는 경우 유료 프롬프트 삭제를 막습니다.
> fix: 프롬프트 삭제 조건 추가 (#208)

- src/prompts/routes/prompt.route.ts
프롬프트 상세보기 접근 권한 수정
권한 수정을 위해 JWT 인증 미들웨어를 제거하였습니다.
> Fix/#215 프롬프트 상세보기 접근 권한 수정

- src/config/passport.ts
- src/members/repositories/member.repository.ts
- src/members/routes/member.route.ts
- src/members/services/member.service.ts
네, 팔로워/팔로잉 목록 조회 시 팔로워 수 추가 기능에 대한 PR 설명을 작성해드리겠습니다!
팔로워, 팔로잉 목록 조회 시 각 프롬프터들의 팔로워 수를 함께 반환하도록 개선했습니다. 이를 통해 사용자는 팔로우하고 있는 사람이나 자신을 팔로우하는 사람의 인기도를 한눈에 파악할 수 있습니다.
- `findFollowersByMemberId()`: 팔로워 목록 조회 시 각 팔로워의 팔로워 수 계산 추가
- `findFollowingsByMemberId()`: 팔로잉 목록 조회 시 각 팔로잉의 팔로워 수 계산 추가
- `findAllMembers()`: 전체 회원 조회 시 프로필 이미지 URL도 함께 반환하도록 개선
- 팔로워 목록: `follower_cnt` 필드 추가
- 팔로잉 목록: `follower_cnt` 필드 추가 (팔로잉하는 사람의 팔로워 수)
- 전체 회원 목록: `profile_image_url` 필드 추가
- 각 사용자별로 개별 팔로워 수를 계산하여 정확한 정보 제공
- Prisma의 `count()` 메서드를 활용하여 효율적인 데이터베이스 쿼리
```json
{
"message": "팔로워 목록 조회 완료",
"data": [
{
"follow_id": 1,
"follower_id": 10,
"nickname": "프롬프트마스터",
"email": "master@example.com",
"follower_cnt": 125,
"created_at": "2025-01-15T10:30:00Z",
"updated_at": "2025-01-15T10:30:00Z"
},
{
"follow_id": 2, …
```
> fix: 팔로워, 팔로잉 목록 조회 시 팔로워 수 반환 응답 추가

- src/members/controllers/member.controller.ts
- src/members/routes/member.route.ts
- src/members/services/member.service.ts
특정 회원 조회하기 API에서 토큰 인증을 삭제하여, 로그인하지 않은 사용자도 회원 정보를 자유롭게 조회할 수 있도록 개선했습니다. 이를 통해 플랫폼의 접근성을 높이고, 회원들의 프로필을 더 쉽게 탐색할 수 있게 되었습니다.
- `GET /api/members/:memberId` 라우트에서 `authenticateJwt` 미들웨어 제거
- 인증 없이도 API 접근이 가능하도록 변경
- `getMemberById` 메서드에서 `requesterId` 파라미터 제거
- `req.user` 의존성 제거로 인증 불필요한 구조로 변경
- `getMemberById` 메서드 시그니처를 `(memberId: number)`로 단순화
- 로그인한 사용자 정보 없이도 회원 조회가 가능하도록 수정
- API 문서에서 `security` 필드 제거
- 인증이 필요하지 않음을 명시하는 설명 추가
- 공개 API임을 명확히 표시
```typescript
// 변경 전 (인증 필요)
router.get("/:memberId", authenticateJwt, memberController.getMemberById);
// 변경 후 (인증 불필요)
router.get("/:memberId", memberController.getMemberById);
```
```typescript
// 변경 전
public async getMemberById(req: Request, res: Response, next: NextFunction) {
const requesterId = (req.user as any).user_id; // 인증 필요 …
```
> fix: 특정 회원 조회하기 API 토큰 인증 제거

- src/auth/services/auth.service.ts
accessToken 유효시간은 3시간에서 24시간으로 바꿨습니다 (개발용)
> fix: accessToken 3h -> 24h

- src/accounts/controllers/account.controller.ts
- src/accounts/dtos/account.dto.ts
> Fix: 요청 형식 수정

- src/accounts/repositories/account.repository.ts
- src/accounts/services/account.service.ts
> Fix: 사용자 계좌 정보 수정 시 중복 계좌 검사 로직 추가

- src/notifications/controllers/notification.controller.ts
- src/notifications/dtos/notification.dto.ts
- src/notifications/routes/notification.route.ts
- src/notifications/services/notification.service.ts
특정 프롬프터 알림 구독 여부를 반환하는 API
- 반환값 existing=false 또는 true로 구독 여부 파악 가능
- db에서 구독 여부를 조회하는 함수는 기존 findSubscribed() 함수 재사용
> [FEAT]: 프롬프터 알림 구독 여부 조회 api 구현

- src/notifications/dtos/notification.dto.ts
- src/notifications/services/notification.service.ts
- 구독 여부 응답 필드
- 기존: existing
- 변경 후: subscribed
> [FIX]: 구독여부 응답 필드 변경(#247)

- src/prompts/controllers/prompt.controller.ts
- src/prompts/services/prompt.service.ts
📌 기능 설명
프롬프트 이미지 매핑 API (POST /api/prompts/{prompt-id}/images)에 권한 체크 및 포괄적인 에러 핸들링을 추가했습니다.
📌 구현 내용
🔐 권한 체크 로직 추가
JWT 인증: 로그인한 사용자만 접근 가능
프롬프트 소유자 확인: 본인이 작성한 프롬프트에만 이미지 매핑 가능
서비스 레이어 권한 검증: getPromptByIdRepo를 활용한 실제 소유권 확인
✅ 입력 유효성 검사 강화
promptId: 숫자, 양수 검증
image_url: 필수 필드, 문자열, 공백 제거
order_index: 선택적 필드, 0 이상 숫자 검증
> modify: 에러 응답 추가

- src/prompts/controllers/prompt.controller.ts
- src/prompts/services/prompt.service.ts
> fix: Bad Request bug 수정

- src/inquiries/dtos/create-inquiry.dto.ts
- src/members/controllers/member.controller.ts
- src/members/dtos/create-sns.dto.ts
> fix/#257 400에러 응답값 수정

- src/auth/services/auth.service.ts
> bug: 회원 정보 로그아웃, 로그인 시에도 유지

- src/auth/services/auth.service.ts
> bug: 회원 정보 수정 후 로그아웃하면 정보 없어지는 버그

- src/accounts/routes/account.route.ts
- src/messages/routes/message.route.ts
- src/purchases/routes/purchase.request.route.ts
> Docs: 스웨거 문서 마저 작성

- src/prompts/repositories/prompt.repository.ts
> fix: review_count 삭제

- package.json
- src/prompts/services/prompt.download.service.ts
- swagger.json
> Fix: Resolved free prompt downloading error

- src/prompts/dtos/prompt.download.dto.ts
- src/prompts/repositories/prompt.download.repository.ts
- src/prompts/services/prompt.download.service.ts
> Fix: Added nickname

- Caddyfile
> fix: 502원인인 caddy 문법 오류 수정

- src/auth/services/auth.service.ts
> /fix : auth error detail 콘솔 출력

- src/messages/controllers/message.controller.ts
- src/messages/routes/message.route.ts
- src/messages/services/message.service.ts
> Feat: 관리자 메시지 전송 기능 구현
